changelog:
  exclude:
    labels:
      - ci
      - chore
      - refactor
  categories:
    - title: Breaking Changes 🚨
      labels:
        - release-major
        - breaking-change
    - title: New Features 🚀
      labels:
        - release-minor
        - enhancement
    - title: Bug Fixes 🐛
      labels:
        - release-patch
        - bug
    - title: Performance Improvements ⚡️
      labels:
        - release-patch
        - perf
    - title: Other Changes
      labels:
        - "*"